version: '3.7'

services:
  terragrunt:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TF_VERSION: 1.5.7
        TG_VERSION: 0.54.0
    image: appdeploy:latest
    volumes:
      - .:/deploy
      - ${HOME}/.aws:/home/appdeploy/.aws
    working_dir: /deploy/tg
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
    entrypoint: ["sh"]
