name: release

on:
  release:
      types:
        - published

env:
  AWS_REGION: ap-southeast-2
  TAG: ${{ github.event.release.tag_name }}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up docker structure test
        run: >
          curl -LO
          https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64
          /usr/local/bin/container-structure-test

      - name: Configure AWS Credentials
        if: ${{ !env.ACT }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Login to ECR
        if: ${{ !env.ACT }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ECR_REGISTRY }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TAG }}

      - name: Test
        run: |
          container-structure-test test --image ${{ env.TAG }} --config tests/config.yaml

      - name: Build and Push
        if: ${{ !env.ACT }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ env.TAG }}
            ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:latest

  render_and_deploy:
    runs-on: ubuntu-latest
    needs: build_test_push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render api definition
        id: render-api-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./templates/api_definition.json
          container-name: api
          image: 450356697252.dkr.ecr.ap-southeast-2.amazonaws.com/api:${{ env.TAG }}
          environment-variables: |
            DJANGO_SECRET_KEY=change_me
            DB_HOST=${{ vars.DB_HOST }}
            DB_NAME=api
            DB_USER=api
            DB_SECRET_NAME=${{ vars.DB_SECRET_NAME }}
            DB_SECRET_REGION=${{ vars.DB_SECRET_REGION }}
            ALLOWED_HOSTS=*
            ALLOWED_CIDR_NETS=10.32.48.0/20,10.32.64.0/20,10.32.80.0/20
            S3_STORAGE_BUCKET_NAME=api-bucket-450356697252
            S3_STORAGE_BUCKET_REGION=ap-southeast-2

      - name: Render nginx proxy definition
        id: render-proxy-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-api-definition.outputs.task-definition }}
          container-name: proxy
          image: 450356697252.dkr.ecr.ap-southeast-2.amazonaws.com/nginx:latest
          environment-variables: |
            APP_HOST=127.0.0.1
            APP_PORT=9000
            LISTEN_PORT=80

      - name: Display Rendered Template
        if: ${{ env.ACT }}
        id: display-rendered-template
        run: cat ${{ steps.render-proxy-definition.outputs.task-definition }} | jq -r

      - name: Deploy to Amazon ECS service
        if: ${{ !env.ACT }}
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-proxy-definition.outputs.task-definition }}
          service: api-service
          cluster: api-cluster
          force-new-deployment: true
          wait-for-service-stability: true
