name: Build and Test

on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker Structure Test
        run: >
          curl -LO
          https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64
          /usr/local/bin/container-structure-test

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ vars.ECR_REPOSITORY }}

      - name: Test Docker Image
        run: |
          container-structure-test test --image ${{ vars.ECR_REPOSITORY }} --config tests/config.yaml
